/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackages;

import java.io.IOException;

/**
 *
 * @author Aqshal-kun
 */
public class MainMenu extends javax.swing.JFrame {
    
    
    /**
     * Creates new form MainMenu
     */
    public String OS = "";
    public MainMenu() {
        initComponents();
        
        OS = System.getProperty("os.name");
        System.out.println(OS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        shutdown = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        restart = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        shutdown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackages/Shutdown-64.png"))); // NOI18N
        shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                shutdownMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shutdown, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shutdown, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 10, 100, 100);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        restart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackages/Restart-64.png"))); // NOI18N
        restart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                restartMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restart, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(140, 10, 100, 100);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackages/Exit-64.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(260, 10, 100, 100);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aqshal-kun\\Downloads\\Cancel-64.png")); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);
        jPanel6.setBounds(380, 10, 100, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        setBounds(0, 0, 513, 170);
    }// </editor-fold>//GEN-END:initComponents

    private void restartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseReleased
        // TODO add your handling code here:
        String commandExec = "";
        
        if (OS.contains("Windows")) {
            commandExec = "shutdown -r -t 90";
        } 
        else if (OS.contains("Linux")) {
            commandExec = "sudo shutdown -r 90";            
        }
        else if (OS.contains("Mac")) {
            commandExec = "sudo shutdown -r 90";
        }
        else {
            System.out.println("OS anda belum tersupport aplikasi ini!");
        }
        
        try{
            Runtime.getRuntime().exec(commandExec);
        }
        catch (IOException e) {
        }
    }//GEN-LAST:event_restartMouseReleased

    private void exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseReleased
        // TODO add your handling code here:
        String commandExec = "";
        
        if (OS.contains("Windows")) {
            commandExec = "shutdown -l -t 90";
        } 
        else if (OS.contains("Linux")) {
            commandExec = "gnome-session-quit --force";            
        }
        else if (OS.contains("Mac")) {
            commandExec = "sudo pkill loginwindow";
        }
        else {
            System.out.println("OS anda belum tersupport aplikasi ini!");
        }
        
        try{
            Runtime.getRuntime().exec(commandExec);
        }
        catch (IOException e) {
        }
    }//GEN-LAST:event_exitMouseReleased

    private void cancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseReleased
        // TODO add your handling code here:
        String commandExec = "";
        
        if (OS.contains("Windows")) {
            commandExec = "shutdown /a";
        } 
        else if (OS.contains("Linux")) {
            commandExec = "sudo shutdown -c";            
        }
        else if (OS.contains("Mac")) {
            commandExec = "sudo killall shutdown";
        }
        else {
            System.out.println("OS anda belum tersupport aplikasi ini!");
        }
        
        try{
            Runtime.getRuntime().exec(commandExec);
        }
        catch (IOException e) {
        }
    }//GEN-LAST:event_cancelMouseReleased

    private void shutdownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutdownMouseReleased
        // TODO add your handling code here:
        String commandExec = "";
        
        if (OS.contains("Windows")) {
            commandExec = "shutdown -s -t 90";
        } 
        else if (OS.contains("Linux")) {
            commandExec = "sudo shutdown -h 90";            
        }
        else if (OS.contains("Mac")) {
            commandExec = "sudo shutdown -h 90";
        }
        else {
            System.out.println("OS anda belum tersupport aplikasi ini!");
        }
        
        try{
            Runtime.getRuntime().exec(commandExec);
        }
        catch (IOException e) {
        }
    }//GEN-LAST:event_shutdownMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel restart;
    private javax.swing.JLabel shutdown;
    // End of variables declaration//GEN-END:variables
}
